### ISSUE TITLE
Модуль 3, задание 2: Download Fiddler

### ISSUE THREAD

**Issue by ghost** [epam-dotnet-lab/northwind-apps#1]
Смущает вопрос [How do you plan to use Fiddler?](https://www.telerik.com/download/fiddler)
Какую опцию нам следует выбирать, и какое это имеет значение?
Влияет ли это на версию установщика?

![Untitled-1](https://user-images.githubusercontent.com/54996068/73967952-f7512b00-4929-11ea-8746-a9d3ce800a83.jpg)

**Comment by alexander-rykov** [comment]
"какое это имеет значение" - никакое. выбирайте любое. но если хотите дать разработчикам правильную статистику - Website development/debugging.
