### ISSUE TITLE
Модуль 4, задание 1: использование Task.Run для запуска

### ISSUE THREAD

**Issue by alexander-rykov** [epam-dotnet-lab/northwind-apps#11]
@jurishev:

Можно ли использовать Task.Run для асинхронного вызова синхронных методов из экшенов контроллера?

```cs
public async Task<ActionResult<IList<Product>>> Get()
{
    return this.Ok(await Task.Run(() => this.service.ShowProducts(0, 0)));
}
```

**Comment by alexander-rykov** [comment]
Вызывать асинхронные методы с помощью Task.Run можно, но делать так, как сделали Вы - не стоит.

Во-первых, нужно задать себе вопрос: "для чего это нужно"? А во-вторых, определить, является ли ShowProducts CPU-bound или IO-bound операцией?

Упростим код:

```cs
private IList<Product> GetMethod() {
    return this.service.ShowProducts(0, 0); // (**)
}

public async Task<ActionResult<IList<Product>>> Get() {
    // <--- (1) caller
    var @delegate = new Func<IList<Product>>(this.GetMethod);
    var result = await Task.Run(@delegate); // (*)
    // <--- (2) a callback
    return this.Ok(result); //(***)
}
```
Метод Get состоит из двух частей:
1) вызов асинхронной операции (caller)
2) колбэк, который вызывается по окончанию асинхронной операции.

Пройдемся отладчиком:

(*) ASP.NET берет свободный поток 4 из пула потоков, который выполняет код экшена и вызывает асинхронную операцию (в нашем случае делегат).
![task-run-async01](https://user-images.githubusercontent.com/19323417/74977555-f77a1c00-543b-11ea-9377-83d2127fb3d5.png)

(**) Task.Run запускает код делегата в свободном потоке 7 из пула потоков. Поток 4 освобождается.
![task-run-async02](https://user-images.githubusercontent.com/19323417/74977572-006aed80-543c-11ea-8fd2-2fbeb52f8215.png)

(***) После завершения асинхронной операции (делегата), код колбэка выполняется в потоке 7. Поток 4 уже полностью освобожден. (Поведение будет разным для ASP.NET Core и ASP.NET)
![task-run-async03](https://user-images.githubusercontent.com/19323417/74977592-08c32880-543c-11ea-97e8-71a8dbb274be.png)

Теперь вернемся к вопросам.

В общем случае, ShowProducts будет IO-bound операцией, которая будет обращаться к БД через драйвера сетевых устройств. При этом операция будет блокирующей, т.е. поток будет заблокирован до получения данных из устройства.

См. про IO-bound операции:
* [Recognize CPU-Bound and I/O-Bound Work](https://docs.microsoft.com/en-us/dotnet/csharp/async#recognize-cpu-bound-and-io-bound-work)
* [Tip 2: Distinguish CPU-Bound work from IO-bound work](https://channel9.msdn.com/Series/Three-Essential-Tips-for-Async/Tip-2-Distinguish-CPU-Bound-work-from-IO-bound-work)

Зачем это надо? В бэк-енд сервисах использование асинхронных неблокирующих IO-операций позволяет экономить системные потоки.

См. [Tip 4: Async Library Methods Shouldn't Lie](https://channel9.msdn.com/Series/Three-Essential-Tips-for-Async/Async-Library-Methods-Shouldn-t-Lie): "In a server app, spinning up threads hurts scalability." Также см. [Анатомия веб-сервиса](https://habr.com/ru/company/oleg-bunin/blog/309324/).

У вас есть два варианта.

Вариант 1 - блокирующая IO-операция. Не использовать async/await и смириться с блокировкой потока на время выполнения I/O операции.

```cs
public ActionResult<IList<Product>> Get() {
    return this.Ok(this.service.ShowProducts(0, 0));
}
```

Вариант 2 - неблокирующая IO-операция. Превратить ShowProducts в асинхронный метод, который будет использовать ToListAsync().

```cs
public async Task<ActionResult<IList<Product>>> Get() {
    return this.Ok(await this.service.ShowProductsAsync(0, 0));
}
```

См. описание проблемы в [Недопонимание про async/await и многопоточность в C#](https://habr.com/ru/post/261649/).

**Comment by ghost** [comment]
Да, выяснилось, что неверное понимание и использование Task.Run() - распространенная проблема новичков в асинхронном программировании :)
Вот хорошие материалы по теме:
https://blog.stephencleary.com/2013/11/taskrun-etiquette-examples-using.html
https://blog.stephencleary.com/2013/11/taskrun-etiquette-examples-dont-use.html
https://habr.com/ru/company/dodopizzadev/blog/435666/

**Comment by alexander-rykov** [comment]
@jurishev:

"Нужды особой делать так именно в данном случае, конечно нет. Потому что контроллер не делает никакой другой операции, кроме как ждет результат от сервиса. Но в случае если бы контроллеру было еще чем заняться, пока сервис работает, этот паттерн вполне пригоден."

Вопрос будет: "Чем именно заняться, CPU или IO-bound?"

Если у вас есть несколько независимых неблокирующих IO-операций, можно использовать Task.WaitAll. Это будет эффективно.

См. [How to extend the async walkthrough by using Task.WhenAll](https://docs.microsoft.com/en-us/dotnet/csharp/programming-guide/concepts/async/how-to-extend-the-async-walkthrough-by-using-task-whenall).
