### ISSUE TITLE
Модуль 4, задание 2: NorthwindContext

### ISSUE THREAD

**Issue by idtitkov** [epam-dotnet-lab/northwind-apps#12]
> Добавьте классы - контекст NorthwindContext и необходимые сущности.

А где взять NorthwindContext? Сгенерировать с БД (с помощью Scaffold-DbContext например) или создать вручную? Если второе, то учитывать ли связи межу таблицами?

> необходимые сущности

Их очень много в Northwind. Подразумевается добавлять/менять их по мере необходимости?

**Comment by alexander-rykov** [comment]
"А где взять NorthwindContext?"

См. [Add the TodoContext database context](https://docs.microsoft.com/en-us/aspnet/core/tutorials/first-web-api?view=aspnetcore-3.1&tabs=visual-studio#add-the-todocontext-database-context).

"Сгенерировать с БД (с помощью Scaffold-DbContext например) или создать вручную?"

Scaffold-DbContext - пока не нужно.

"Если второе, то учитывать ли связи межу таблицами?"

Да.

"Их очень много в Northwind. Подразумевается добавлять/менять их по мере необходимости?"

Вам для выполнения достаточно 2х сущностей - Product и Category. В последнем задании - Employee.
