### ISSUE TITLE
Модуль 4, задание 3: не получается визуализировать изображение

### ISSUE THREAD

**Issue by ghost** [epam-dotnet-lab/northwind-apps#13]
Categories.Picture - байты из базы данных извлекаются и Postman их получает, но сама картинка не отображается. Не могу разобраться в чем проблема.

**Comment by ghost** [comment]
Нашел решение. Оказывается, это как-то связано с Microsoft Access. Перед отправкой изображений из Northwind нужно обрезать первые 78 байт, и посылать как image/bmp.

**Comment by alexander-rykov** [comment]
Верно, данные изображения состоят из OLE header (78 байт) и BMP.
https://mathematica.stackexchange.com/questions/184743/how-to-extract-bitmap-image-from-sql-records
