### ISSUE TITLE
Модуль 3, задание 5: CurrencyLayer access restricted

### ISSUE THREAD

**Issue by adrowsychild** [epam-dotnet-lab/northwind-apps#15]
Здравствуйте!

В качестве ответа от currencylayer.com приходит сообщение: 
{"success":false,"error":{"code":105,"info":"Access Restricted - Your current Subscription Plan does not support this API Function."}}

пример запроса:
https://api.currencylayer.com/convert?access_key=eea8ca047310d2e984af62c2e2eef67f&from=BYN&to=EUR&amount=1

аккаунт зарегистрирован успешно под FreePlan, API Usage 0% (0/250)

как можно решить проблему?

**Comment by alexander-rykov** [comment]
[API "Currency Conversion" недоступен для Free Plan](https://currencylayer.com/product).

Вам нужен endpoint, который используется в статье "Осваиваем async/await..."

**Comment by adrowsychild** [comment]
спасибо за быстрый ответ!
