### ISSUE TITLE
Модуль 1, задание 2: Learning OData on Postman - вопросы по некоторым запросам

### ISSUE THREAD

**Issue by vysotnikolay** [epam-dotnet-lab/northwind-apps#16]
Добрый день, Александр!
Пытаюсь разобраться с TripPin из коллекции примеров, импортированных из этой ссылки [https://www.getpostman.com/collections/705714417adde4e687e4](url)
В частности, при попытке добавления пользователя по этому запросу 
![image](https://user-images.githubusercontent.com/58489867/82873326-0261b280-9f3d-11ea-9025-570535a23233.png)
по моему пониманию должен добавляться соответствующий пользователь в коллекции. 
И в теле ответа на вышеуказанный POST-запрос возвращаются все пользователи (Mia Thompson отсутствует).
При запросе GET http://services.odata.org/V4/TripPinService/People в теле ответа я также не нашёл Mia Thompson (возвращается 8 пользователей)
Также при запросе GET http://services.odata.org/V4/TripPinService/People/$count каждый раз возвращается 20, а не 8.
В ответе сервера на метод PATCH http://services.odata.org/V4/TripPinService/People('miathompson') возвращается статус 204 - No Content.
Понятно, что сервис учебный, но если так и должно быть, то уж слишком много косяков.
Или же я делаю что-то не так?

**Comment by alexander-rykov** [comment]
Давайте по порядку:

1) Запрос $count возвращает общее количество сущностей в системе - 20 единиц.

`GET http://services.odata.org/V4/TripPinService/People/$count`

Запрос /People возвращает список сущностей, однако количество сущностей для запроса ограничено по-умолчанию - 8 единиц.

`GET http://services.odata.org/V4/TripPinService/People`

Обратите внимание на поле @odata.nextLink в ответе:

`
"@odata.context": "http://services.odata.org/V4/TripPinService/$metadata#People",
"@odata.nextLink": "https://services.odata.org/V4/TripPinService/People?%24skiptoken=8",
`

Параметр skiptoken говорит сервису, что нужно пропустить первые 8 сущностей. Следовательно, при вызове по этому URL вы получите следующие 8 cущностей. Во втором ответе будет ссылка на след. вызов.

`
"@odata.nextLink": "https://services.odata.org/V4/TripPinService/People?%24skiptoken=16"
`

Такой подход называется pagination - https://www.google.com/search?q=pagination+rest+api.

См. также "15. Client-side paging" в коллекции "Postman OData Tutorial".

**Comment by alexander-rykov** [comment]
2) "по моему пониманию должен добавляться соответствующий пользователь в коллекции"

В документации [сказано](https://www.odata.org/odata-services/):

> Data Modification
> 
> Notice: During the following sections, you are going to modify the data of Trippin service. To prevent other users’ actions affect your results, you need to request a key firstly to identify yourself to the server. Otherwise, the results of your actions are unpredictable. The way to request a key is introduced here.

Далее - см. [Request A Key To Identify Yourself to Trippin](https://www.odata.org/odata-services/service-usages/request-key-tutorial/).

В документации есть ссылка на отдельную коллекцию - "Trippin Basic Usages with Key", однако коллекция не рабочая и ее нужно дорабатывать.

Я загрузил "... with Key" коллекцию в Postman, установил параметр key environment variable в настройках коллекции (edit collection -> variables), заменил протокол на https и добавил параметр в путь.

![Annotation 2020-05-26 123920](https://user-images.githubusercontent.com/19323417/82885943-7d7f9480-9f4e-11ea-8e0d-583c63d4011c.png)

Все заработало - **Status: 201 Created**.

Запрос $count выдает количество сущностей - 21.

![Annotation 2020-05-26 124553](https://user-images.githubusercontent.com/19323417/82886338-16aeab00-9f4f-11ea-8a5c-6cd24c6936ec.png)

Запрос сущности по ID возвращает данные сущности:

![Annotation 2020-05-26 124917](https://user-images.githubusercontent.com/19323417/82886815-bc621a00-9f4f-11ea-89b4-dce23d5dca63.png)

**Comment by alexander-rykov** [comment]
3. "В ответе сервера на метод PATCH http://services.odata.org/V4/TripPinService/People('miathompson') возвращается статус 204 - No Content."

Для корректной работы PATCH также необходим ключ и смена протокола на https:

![Annotation 2020-05-26 125616](https://user-images.githubusercontent.com/19323417/82887436-aacd4200-9f50-11ea-9309-4689a248c473.png)

Проверка изменений:

![Annotation 2020-05-26 125755](https://user-images.githubusercontent.com/19323417/82887478-bcaee500-9f50-11ea-9efc-08d7ea6d7123.png)
