### ISSUE TITLE
Модуль 3, задание 5.3: CurrencyExchangeService и сервис CurrencyLayer

### ISSUE THREAD

**Issue by vysotnikolay** [epam-dotnet-lab/northwind-apps#17]
Добрый день, Александр!
Смущают некоторые вопросы по поводу реализации метода
`public async Task<decimal> GetCurrencyExchangeRate(string baseCurrency, string exchangeCurrency)`
класса _CurrencyExchangeService_.
По заданию метод должен возвращать результат выполнения асинхронной задачи Task<decimal> - курс конверсии из базовой в целевую валюту, в качестве аргументов принимая строковые представления кодов валют.
В моём понимании по заданию получается, что на каждую новую пару валют в CurrencyLayer отправляется новый запрос. Базовая валюта в нашем случае постоянная - USD. Если нужно получить 5-10 товаров - всё ок, не вижу проблем. Однако если товаров 1 000 000? Получаем необходимость соответствующего количества запросов к сервису CurrencyLayer, к тому же более 250 запросов в месяц - уже платно.
Вариант решения этой проблемы - отправить запрос (например, при создании объекта CurrencyExchangeService) `http://api.currencylayer.com/live?access_key=<access_key>&format=1`, ответом на который получаем словарь курсов конверсий к USD (или же если нужна другая базовая валюта, то указать `&source=<source_currency>`, только это опять же в платной версии) и закэшировать ответ. Далее уже словарём конверсий пользоваться в методе GetCurrencyExchangeRate.
Но тогда отпадает необходимость делать GetCurrencyExchangeRate асинхронным, т.к. данные конверсии закэшированы.

1. Какой вариант предпочтительнее?
2. Применяют ли на практике такой подход - при создании объекта сервиса отправлять запрос к внешнему сервису и кэшировать его результат?

**Comment by alexander-rykov** [comment]
Здравствуйте!

_Какой вариант предпочтительнее?_

Имеется ввиду - "с кешированием" или "без кеширования"? Для данного задания нет разницы. Если хотите, сделайте кеширование.

_Применяют ли на практике такой подход - при создании объекта сервиса отправлять запрос к внешнему сервису и кэшировать его результат?_

Применяют. Можно реализовывать кеширование как [in process с использованием классов BCL](https://docs.microsoft.com/en-us/dotnet/framework/performance/caching-in-net-framework-applications), так и во внешнем приложении ([Redis](https://redis.io/))
