### ISSUE TITLE
Модуль 3, задание 1.6: Помарка в конструкторе класса ProductReport

### ISSUE THREAD

**Issue by vysotnikolay** [epam-dotnet-lab/northwind-apps#18]
Добрый день, Александр!
Есть помарка в этом конструкторе:
```
public ProductReport(IEnumerable<T> products)
        {
            this.Products = products.ToArray() ?? throw new ArgumentNullException(nameof(products));
        }
```
https://github.com/epam-dotnet-lab/northwind-apps/blob/04f5a088571d1336bf56a52159f949ff5aeb1073/module03/ReportingApps/Northwind.ReportingServices.OData/ProductReports/ProductReport.cs#L27
По идее должно быть так:
`...products?.ToArray() ?? ...`
Потому что иначе мы получим исключение ArgumentNullException из метода расширения System.Linq.Enumerable.ToArray<TSource>(this IEnumerable<TSource> source)

**Comment by vysotnikolay** [comment]
Естественно, имею ввиду случай, когда в _products_ приходит _null_

**Comment by alexander-rykov** [comment]
Да, все верно - нужно проверять (products is null). Спасибо!
