### ISSUE TITLE
Модуль 4, задание 2.6 и 2.7: вопрос по IProductManagementService и ProductManagementService

### ISSUE THREAD

**Issue by vysotnikolay** [epam-dotnet-lab/northwind-apps#19]
Добрый день, Александр!
Методы ProductManagementService должны обращаться к контексту базы данных. Можно ли изменить сигнатуры методов интерфейса и сервиса, чтобы сделать методы асинхронными? Соответственно, в контроллере уже будет обращение к асинхронным awaitable-методам.
Заранее спасибо за ответ.

**Comment by alexander-rykov** [comment]
см. "Задание 5". :)
