### ISSUE TITLE
Модуль 2, минорные предложения

### ISSUE THREAD

**Issue by idtitkov** [epam-dotnet-lab/northwind-apps#2]
Задание 2.

> 1. Создайте новое консольное приложение .NET Core, сгенерируйте код клиента, добавьте код в Program.Main и запустите приложение.

Тут стоит указать название приложения, которое нужно создать - "TripPinUnchaseCoreClient", т.к. нему есть ссылка в Задании 6.

Задание 5.

> 1. Примените подход APM к коду клиента...

Возможно, стоит указать, что речь идет о коде из "NorthwindServiceCoreClient".

> 2. Примените подход TAP к коду клиента...

Аналогично, можно напомнить, что речь про "NorthwindServiceCoreAsyncClient".

**Comment by alexander-rykov** [comment]
Спасибо. Исправил.
