### ISSUE TITLE
Модуль 4, задание 3.2: Возможно кому-нибудь будет полезна информация.

### ISSUE THREAD

**Issue by vysotnikolay** [epam-dotnet-lab/northwind-apps#20]
При регистрации сервисов
```
services.AddScoped((service) =>
{
    var sqlConnection = new SqlConnection(@"Data Source=(localdb)\MSSQLLocalDB;Initial Catalog=Northwind;Integrated Security=True;Connect Timeout=30;Encrypt=False;TrustServerCertificate=False;ApplicationIntent=ReadWrite;MultiSubnetFailover=False");
    sqlConnection.Open();
    return sqlConnection;
});

services.AddTransient<DataAccess.NorthwindDataAccessFactory, DataAccess.SqlServerDataAccessFactory>();
```
столкнулся с такой проблемой:
![image](https://user-images.githubusercontent.com/58489867/91532164-97968d80-e916-11ea-9523-c20c0cc7f9b6.png)

Потерял пару часов, прежде чем решил её. Корень проблемы был в невнимательности при использовании директивы using для импорта пространства имён. Тип _SqlClient_ есть в двух пространствах имён - _**System.Data**_ и _**Microsoft.Data**_. В классе _SqlServerDataAccessFactory_ используется _SqlClient_ из пространства _System.Data_, а в _Startup_ я импортировал из пространства _Microsoft.Data_. Естественно, не удалось в DI-контейнере разрешить нужную зависимость.
Долго искал ошибку, гуглил, ничего не получалось, пока не написал это:
```
            services.AddTransient<NorthwindDataAccessFactory>(provider =>
            {
                var sqlConnection = new SqlConnection(ConnectionString);
                sqlConnection.Open();
                return new SqlServerDataAccessFactory(sqlConnection);
            });
```
Тут уже помог компилятор, подсказав, что это разные типы и всё стало на свои места.
Будьте внимательны! Не наступайте на мои грабли :)

P.S.: Полезная и интересная статья на тему DI: [New in ASP.NET Core 3: Service provider validation](https://andrewlock.net/new-in-asp-net-core-3-service-provider-validation/)

**Comment by alexander-rykov** [comment]
Спасибо!
