### ISSUE TITLE
Модуль 5, задание 4.9: Непонятное поведение (exception) после добавления BloggingContext

### ISSUE THREAD

**Issue by vysotnikolay** [epam-dotnet-lab/northwind-apps#21]
Добрый день, Александр!
Возникла следующая проблема:

> 9. Добавьте реализацию в BlogArticle, IBloggingService, BloggingService и BlogArticlesController для операции Create. Дата и время добавления статьи вычисляются автоматически на основе системного времени сервера, на котором происходит запуск back-end приложения.

После регистрации BloggingContext и BloggingService перестают работать запросы к другим сервисам (EmployeeManagementService и т.д.). При обращении к ним возникает следующее исключение: **SqlException: Invalid object name 'Employees'.**  Точно такие же возникают с Products, ProductCategories.
Во всех случаях источником исключения является обращение к свойствам контекста БД, например, такое в случае с EmployeeManagementService.cs:

`var employees = await this.context.Employees.ToListAsync();`

Как только убираю из регистрации в Startup всё, что связано с Blogging - всё снова работает как надо.
Может подскажете как победить?

**Comment by alexander-rykov** [comment]
подозрительно. залейте ваш код в репозиторий, я посмотрю.
https://github.com/vysotnikolay/northwind-apps - это здесь?

**Comment by alexander-rykov** [comment]
а миграции точно есть?
https://entityframeworkcore.com/knowledge-base/43855004/sqlexception--invalid-object-name--movie-

**Comment by vysotnikolay** [comment]
> подозрительно. залейте ваш код в репозиторий, я посмотрю.
https://github.com/vysotnikolay/northwind-apps - это здесь?

Нет, это форк самого задания с вашего репозитория. Сегодня расшарю, прямо сейчас нет возможности.

UPD:
Открыл Вам доступ.
[https://github.com/vysotnikolay/Northwind-Web-API/tree/module5](url)

**Comment by vysotnikolay** [comment]
> а миграции точно есть?
> https://entityframeworkcore.com/knowledge-base/43855004/sqlexception--invalid-object-name--movie-

Да, миграции есть. БД Blogging точно создана - в SQL Server Object Explorer она отображается.
UPD:
Возможна ли проблема из-за того, что я вручную экспериментировал с БД Blogging, меняя в одном из полей флаг null на not null? (на момент inicial миграции поле в БД и в BlogArticel было nullable, затем я изменил на not null и там, и там.)
Вернул это поле в исходное состояние - результат тот же.
В любом случае непонятна связь с регистрацией\отсутствием регистрации связанных с BloggingContext классов - убираю регистрацию - исключение не выбрасывается.
UPD1:
Выполнил начальную миграцию с нуля - всё равно то же исключение выбрасывается, т.е. мои эксперименты, описанные выше - не причина.

**Comment by vysotnikolay** [comment]
Также не совсем понятен вот этот пункт:

> 6. В файл DesignTimeBloggingContextFactory.cs добавьте фабрику для производства контекста BloggingContext, который будет использован для миграций. Это необходимо, так как миграции будут размещены в отдельном проекте. См. Add an implementation of IDesignTimeDbContextFactory и Environment Variables Configuration Provider.

Фабрика отрабатывает, BloggingContext производится, миграция ожидаемо создаётся в активном проекте Northwind.Services.EntityFrameworkCore.Blogging. Непонятно что имеется ввиду под размещением миграций в отдельном проекте. Ссылка [Add an implementation of IDesignTimeDbContextFactory](https://codingblast.com/entityframework-core-idesigntimedbcontextfactory/) не работает уже, к сожалению.
![image](https://user-images.githubusercontent.com/58489867/100517933-693b7f00-319f-11eb-9c3e-b7626be3be1a.png)

**Comment by vysotnikolay** [comment]
Ещё дополнение. Добавил метод проверить GET запрос - он работает с Blogging. POST не работает, т.к. там идёт проверка на наличие указанного Employee в Northwind - то же исключение с текстом _Invalid object name 'Employees'._
Проверил в режиме отладки по запросу POST - NorthwindContext в EmployeeManagementService инициализируется в конструкторе без всяких происшествий, все свойства есть.

**Comment by alexander-rykov** [comment]
ваша проблема здесь:

```
string connectionString = this.Configuration.GetConnectionString(NorthwindContext);
services.AddControllers();

// services.AddScoped((service) =>
// {
//     var sqlConnection = new SqlConnection(connectionString);
//     sqlConnection.Open();
//     return sqlConnection;
// });

services.AddDbContext<NorthwindContext>(o => o.UseSqlServer(connectionString));
connectionString = this.Configuration.GetConnectionString(BloggingContext);
services.AddDbContext<BloggingContext>(o => o.UseSqlServer(connectionString));
```

я изменил код и теперь он рабочий:

```
services.AddControllers();

string northwindConnectionString = this.Configuration.GetConnectionString(NorthwindContext);
services.AddDbContext<NorthwindContext>(o => o.UseSqlServer(northwindConnectionString));

var bloggingConnectionString = this.Configuration.GetConnectionString(BloggingContext);
services.AddDbContext<BloggingContext>(o => o.UseSqlServer(bloggingConnectionString));
```

чтобы разобраться, почему так происходит поставьте брейкпоинт прямо на строках o.UseSqlServer(connectionString) и o.UseSqlServer(connectionString2)

![image](https://user-images.githubusercontent.com/19323417/100523320-b845dc00-31c0-11eb-8d18-86c3a3414ce0.png)

**Comment by alexander-rykov** [comment]
_Ссылка Add an implementation of IDesignTimeDbContextFactory не работает уже, к сожалению._

магия web archive делает чудеса:
https://web.archive.org/web/20200810105531/https://codingblast.com/entityframework-core-idesigntimedbcontextfactory/

**Comment by vysotnikolay** [comment]
> чтобы разобраться, почему так происходит поставьте брейкпоинт прямо на строках o.UseSqlServer(connectionString) и o.UseSqlServer(connectionString2)

Кажется дошло без брейкпоинов. Захват внешнего контекста, при использовании лямбды. Вроде и знаю про это, но упустил... Век живи - век учись )))
Спасибо за помощь!
