### ISSUE TITLE
Модуль 3, задание 3: метод GetContinuation

### ISSUE THREAD

**Issue by NikolayDenisevich** [epam-dotnet-lab/northwind-apps#22]
Непонятно, как в рамках поставленной задачи работать с методом GetContinuation. Метод дан, а как его применить в задаче не ясно.

**Comment by alexander-rykov** [comment]
Думайте. Для начала стоит изучить примеры в статьях и на странице документации. Возможно, потребуется запустить эти примеры в отдельном приложении, чтобы разобраться в механизме работы метода.
