### ISSUE TITLE
Модуль 1, задание 4: уточнение по выполнению

### ISSUE THREAD

**Issue by idtitkov** [epam-dotnet-lab/northwind-apps#3]
Задание 4.
В задании ссылка на "Northwind OData Service" ведет на ресурс работающий про протоколу V2. Только с ним выполнять задание? С V4 ведь можно повыполнять запросы посложнее, например с лямбдами.
Также, в таблице 2 раза повторяется запрос "Get a customer for an order with "10248" id."

**Comment by alexander-rykov** [comment]
Да, старая версия - испрвил на V3.
