### ISSUE TITLE
Модуль 2, задание 2: Использование делегата AsyncCallback

### ISSUE THREAD

**Issue by ArtemGorodk01** [epam-dotnet-lab/northwind-apps#4]
Во втором пункте второго задания для ожидания завершения асинхронной операции используется AsyncWaitHandle, как показано в [статье из документации]( https://docs.microsoft.com/ru-ru/dotnet/standard/asynchronous-programming-patterns/blocking-application-execution-using-an-asyncwaithandle). 
Весь полезный код (код отображения работников) вынесен в делегат AsyncCallback. Если я правильно понял, то этот делегат выполняется в потоке из пула после того, как асинхронная операция считается выполненной.
Получается, что если  код <code> WaitHandle.WaitAny(new[] { asyncResult.WaitHandle });</code> из примера вызвать в конце потока, то код из AsyncCallback выполняться не будет.
Самым простым решением вижу добавление флага <code>isCallBackExecuted</code> как [здесь](https://gist.github.com/ArtemGorodk01/dae014ac71d5b478ff11c36e3097cb7b).
У меня большого опыта в асинхронном программировании нет, поэтому если я где-то ошибся, буду благодарен, если объясните и/или направите на нужную информацию.

**Comment by ArtemGorodk01** [comment]
Немного поразмыслив, я понял, что в задании и не требовалось, чтобы код из AsyncCallback выполнялся в любом случае.
Но вопрос всё же остался, как гарантировать выполнение кода из AsyncCallback более изящным способом, чем я предложил выше?

**Comment by ArtemGorodk01** [comment]
Получил ответ в задании 6. Спасибо)

**Comment by alexander-rykov** [comment]
То, что вы сделали в примере, называется _spinning_. См. секцию [Blocking Versus Spinning](http://www.albahari.com/threading/part2.aspx#_Blocking_Versus_Spinning).

_In general, this is very wasteful on processor time: as far as the CLR and operating system are concerned, the thread is performing an important calculation, and so gets allocated resources accordingly!_

В задании 6 проблема решается через _signaling_. См. примеры в секции [Signaling with Event Wait Handles](http://www.albahari.com/threading/part2.aspx#_Signaling_with_Event_Wait_Handles).

PS: Спасибо за вопрос. Я ждал, кто первый задаст вопрос по этой теме!
