### ISSUE TITLE
Модуль 3, задание 3:  абзац 6 - полный список товаров из сервиса

### ISSUE THREAD

**Issue by idtitkov** [epam-dotnet-lab/northwind-apps#5]
А абзаце 6, где предлагается получить полный список товаров с помощью GetContinuation(), ссылки на статьи ведут на синхронную реализацию такой задачи. Асинхронная значительно сложнее описана тут: https://docs.microsoft.com/en-us/odata/client/async-operations.
Каким способом нам ее реализовывать, синхронным или асинхронным?
И есть ли какие-то еще уточнения по реализации, например можно ли затрагивать Program, или вносить изменения только в GetCurrentProductsReport()?

**Comment by alexander-rykov** [comment]
_Каким способом нам ее реализовывать, синхронным или асинхронным?_

А у вас синхронный способ работает?

_И есть ли какие-то еще уточнения по реализации, например можно ли затрагивать Program, или вносить изменения только в GetCurrentProductsReport()?_

Можно. А зачем?

**Comment by idtitkov** [comment]
Т.к. наше задание на .NET Core, то синхронный способ конечно не работает. Но и приведенные ссылки не очень помогают, т.к. там описан именно синхронный.
По поводу Program, я имел ввиду, надо ли выводить как-то типа "Page 1: ..." или все одним списком.

**Comment by alexander-rykov** [comment]
_Но и приведенные ссылки не очень помогают, т.к. там описан именно синхронный_

Использовать асинхронный метод вы должны уметь, а для того, чтобы применить асинхронный подход и GetContinuation нужно немного терпения и несколько попыток. В этом и состоит задача. Не все же время заниматься копипастой :)

_По поводу Program, я имел ввиду, надо ли выводить как-то типа "Page 1: ..." или все одним списком._

Page 1 - это страница с чем?

**Comment by idtitkov** [comment]
Сервис выдает по 20 записей на страницу. Надо ли их как-то разграничивать (например пустой строкой) при выдаче или можно не заморачиваться?)

**Comment by alexander-rykov** [comment]
не заморачиваться, одним списком
