### ISSUE TITLE
Модуль 2, задание 6: Причина ошибки синхронизации

### ISSUE THREAD

**Issue by Tork2048** [epam-dotnet-lab/northwind-apps#6]
Приветствую!
Вопрос по следующей строке:

Это происходит из-за того, что вызов EndExecute в паралелльном потоке разблокирует основной поток, который заблокирован вызовом метода WaitAny, раньше чем произойдет печать списка.

Данное утверждение противоречит документации, а также личным экспериментам с кодом.
EndExecute блокирует поток, из которого был вызван, до завершения асинхронной операции.

В данном же примере метод EndExecute вызывается из делагата AsyncCallback, который, в свою очередь, вызывается уже после того, как асинхронная операция завершена (asyncResult.AsyncWaitHandle).
Таким образом, в рамках данного примера EndExecute не оказывает никакого влияния на какой-либо поток. Главный поток разблокируется практически одновременно с вызовом делагата AsyncCallback, поэтому и вывод в консоль "Press any key to continue" происходит перед выводом данных из сервиса.

Поправьте, если я ошибаюсь.
Спасибо.

**Comment by alexander-rykov** [comment]
_Таким образом, в рамках данного примера EndExecute не оказывает никакого влияния на какой-либо поток _

верно. пришлите текст, который вы считаете правильным.

**Comment by Tork2048** [comment]
Это происходит из-за того, что главный поток разблокируется сразу же после завершения асинхронной операции BeginExecute путем посылки сигнала объекту asyncResult.AsyncWaitHandle, что прекращает удержание главного потока методом WaitHandle.WaitAny.
Делегат AsyncCallback вызывается после завершения асинхронной операции и его код выполняется в том же параллельном потоке. Таким образом, код делегата и код главного потока выполняются параллельно.

Вышло не очень локанично, но лучше ничего не придумал.

**Comment by alexander-rykov** [comment]
@Tork2048: мбыть так?

Это происходит из-за того, что главный поток, который заблокирован вызовом WaitHandle.WaitAny, разблокируется после завершения асинхронной операции, начатой методом BeginExecute. Делегат AsyncCallback, который передается с помощью лямбда-функции к BeginExecute, вызывается после завершения асинхронной операции и его код выполняется в параллельном потоке. Таким образом, код анонимного делегата и код главного потока выполняются параллельно.

**Comment by Tork2048** [comment]
Да, все понятно.
Спасибо =)
