### ISSUE TITLE
Модуль 3, задание 6: извлечение интерфейса из ProductReportService 

### ISSUE THREAD

**Issue by idtitkov** [epam-dotnet-lab/northwind-apps#7]
> Извлеките методы класса ProductReportService в интерфейс IProductReportService. Реализуйте интерфейс в классе сервиса. Переместите зависимые классы в сборку Northwind.ReportingService.

Надо ли извлекать ВСЕ методы из класса ProductReportService в IProductReportService?
Проблема с методом GetCurrentProductsWithLocalCurrencyReport.

Дело в том, что в соответствии со схемой из данного параграфа (и последующих), проект ReportingService(который общий для OData и Sql) не содержит ссылок на другие проекты, соответственно не видит их неймспейсы. А без этого не сможет содержать в себе метод GetCurrentProductsWithLocalCurrencyReport (т.к после Method Injection он принимает в качестве параметров объекты интерфейсов из проекта CurrencyServices, на который в таком случае нужна ссылка).

Нужно или добавлять в ProductReportService  ссылку на CurrencyServices? (тогда нужно перерисовывать схемы) Или не извлекать этот метод, а добавлять в классы, реализующие IProductReportService, но это не логично.

**Upd:** Судя по параграфам ниже, этот метод предполагается действительно пропустить и заменить классом CurrentProductLocalPriceReport, вопрос снимается, но все равно выглядит не очень логично, т.к. только один метод получит возможность взаимодействовать с разными сервисами, остальные пока привязаны к OData.

**Comment by alexander-rykov** [comment]
Действительно, ReportingService нужна зависимость на CurrencyServices, чтобы использовать интерфейсы из этой сборки.

Добавил абзац в модуль 3 и добавил референс на картинку reportingservices-sqlserver.png.

Теперь все верно?

**Comment by idtitkov** [comment]
Да, но есть еще нюанс: класс ProductReportService для Sql и OData называется одинаково, что приводит к конфликту имен. Приходится обращаться к нему по полному имени.

Также не указано, как реализовать выбор между источниками данных. На свое усмотрение?

И по поводу Composition Root. К концу модуля не могу выделить его, как-то все размазано по Program.

**Comment by alexander-rykov** [comment]
1) "Приходится обращаться к нему по полному имени"

Есть 2 варианта:
* использовать имя с неймспейсом.
* alias при помощи using.

2) "Также не указано, как реализовать выбор между источниками данных"

Не нужно. Достаточно того, что вы попробуете запустить приложение в разных режимах.

3) "К концу модуля не могу выделить его, как-то все размазано по Program"

Класс Program и есть CR.

**Comment by idtitkov** [comment]
Понятно, тогда по этой теме вопросов пока больше нет.
