### ISSUE TITLE
Модуль 3, задание 5: использование JsonDocument для разбора ответа REST-сервисов

### ISSUE THREAD

**Issue by ArtemGorodk01** [epam-dotnet-lab/northwind-apps#9]
В задании есть указание использовать JsonSerializer для разбора полученного из сервиса json-документа. 
Можно ли использовать JsonDocument для разбора полученного из сервиса ответа?
Такой подход кажется более простым, так как не нужно создавать промежуточные модели для десериализации сложного по структуре json-документа и потом отображать их на модели нашего сервиса. Вместо этого можно достать из JsonDocument значение необходимого свойства и положить его сразу в модель нашего сервиса.
В чем плюсы и минусы одного и другого подходов и когда какой следует использовать?

**Comment by alexander-rykov** [comment]
Для этого задания можно было бы использовать и JsonDocument, однако мне хотелось бы видеть сериализацию/десериализацию при помощи моделей.

_В чем плюсы и минусы одного и другого подходов и когда какой следует использовать?_

Модели обычно используют, когда сервис возвращает определенную структуру и когда есть необходимость хранить возвращаемые сервисом данные (передавать их в другие компоненты системы).
